"""Cluster Launch Control (CLC) tile scheduler for core Triton.

CLC is a Blackwell (SM100+) hardware feature for dynamic persistent kernels: a
block that finishes early issues ``clusterlaunchcontrol.try_cancel`` to cancel a
pending (not-yet-launched) cluster and take over its tile. Canceling pending
clusters is what absorbs over-provisioned / jagged tiles -- the ones a
non-persistent kernel would launch and early-``return`` on.

This module exposes a small, opaque scheduler:

    sched = tl.clc_tile_scheduler()     # initialize
    while sched.is_valid():             # loop condition
        m = sched.tile_id[0]            # current tile coord (x); [1]/[2] for y/z
        sched.try_cancel()              # request the next tile (async)
        ... compute tile m ...
        sched = sched.advance()         # make the requested tile current

The response buffer, mbarrier, phase and 128-bit CLC result are all generated by
the compiler and threaded through the ``scf.while`` automatically; the kernel
author never allocates or tracks any of them. This API is standalone -- it does
NOT require warp specialization.
"""
from typing import List, Tuple

import triton.language.core as tl
from triton.language.core import base_value, base_type, builtin, constexpr, tensor
from triton import knobs

__all__ = ["clc_tile_scheduler", "ClcTileScheduler"]

# A CLC response is a 128-bit (16-byte) payload.
_CLC_RESPONSE_BYTES = 16


class _opaque_type(base_type):
    """Type of a value that wraps a single opaque IR handle, remembering its MLIR
    type so it can be threaded through control flow (``scf.while`` iter_args).

    Used for the i128 CLC result and the SMEM response / barrier descriptors --
    none of which the kernel author ever sees.
    """

    def __init__(self, ir_type):
        self.ir_type = ir_type

    def __eq__(self, other) -> bool:
        return isinstance(other, _opaque_type) and self.ir_type == other.ir_type

    def __hash__(self):
        return hash(("clc_opaque", str(self.ir_type)))

    def __str__(self) -> str:
        return "clc_opaque"

    def to_ir(self, builder) -> None:
        return self.ir_type

    def _flatten_ir_types(self, builder, out: List) -> None:
        out.append(self.ir_type)

    def _unflatten_ir(self, handles: List, cursor: int) -> Tuple["_opaque_value", int]:
        return _opaque_value(handles[cursor], self.ir_type), cursor + 1

    def mangle(self) -> str:
        return "CLCoq"


class _opaque_value(base_value):
    """Value wrapping a single opaque IR handle (i128 result or SMEM descriptor)."""

    def __init__(self, handle, ir_type=None):
        self.handle = handle
        self.type = _opaque_type(ir_type if ir_type is not None else handle.get_type())

    def _flatten_ir(self, handles: List) -> None:
        handles.append(self.handle)


class _tile_id_accessor(base_value):
    """Ephemeral proxy returned by ``scheduler.tile_id`` to support ``[dim]``.

    Never flattened / loop-carried -- it is created on attribute access and
    immediately subscripted.
    """

    def __init__(self, scheduler):
        self._scheduler = scheduler
        self.type = None

    def _flatten_ir(self, handles: List) -> None:  # pragma: no cover - never called
        raise TypeError("tile_id is not a value; index it as tile_id[dim]")

    @builtin
    def __getitem__(self, dim, _semantic=None):
        if isinstance(dim, constexpr):
            dim = dim.value
        dim = int(dim)
        if dim < 0 or dim > 2:
            raise IndexError("tile_id dimension must be 0, 1 or 2")
        return self._scheduler._program_id(dim, _semantic=_semantic)


@tl._aggregate
class ClcTileScheduler:
    # All fields are compiler-managed plumbing -- author never writes them.
    _valid: tensor  # i1: whether the current tile is real work (loop condition)
    _clc_result: _opaque_value  # i128: response for the current tile
    _iter: tensor  # i32: monotonic counter driving phase / buffer index
    _responses: _opaque_value  # SMEM ring of i128 CLC responses
    _barriers: _opaque_value  # SMEM ring of "full" mbarriers
    _depth: constexpr  # prefetch depth (TRITON_WS_TILE_PREFETCH_DEPTH)

    @builtin
    def is_valid(self, _semantic=None):
        """Whether the current tile holds real work. Use as the ``while`` condition."""
        return self._valid

    @builtin
    def _program_id(self, dim, _semantic=None):
        """Program id of the current tile along ``dim`` (0=x, 1=y, 2=z).

        Decoded lazily per dim so unused dims are never emitted. The first tile
        comes from the static launch (``program_id``); subsequent tiles from the
        CLC response.
        """
        b = _semantic.builder
        seed = b.create_get_program_id(dim)
        decoded = b.create_clc_get_program_id(self._clc_result.handle, dim)
        zero = b.get_int32(0)
        is_first = b.create_icmpEQ(self._iter.handle, zero)
        return tl.tensor(b.create_select(is_first, seed, decoded), tl.int32)

    @builtin
    def try_cancel(self, _semantic=None):
        """Attempt to cancel a pending cluster and claim its tile (async).

        Issues ``clusterlaunchcontrol.try_cancel`` on the current slot and arms
        the "full" barrier. ``advance`` collects the result. Issue this early in
        the loop body so the CLC latency overlaps compute.
        """
        b = _semantic.builder
        resp = self._responses.handle  # depth == 1: single slot
        bar = self._barriers.handle
        b.create_clc_try_cancel(resp, bar, True)
        b.create_clc_barrier_expect(bar, _CLC_RESPONSE_BYTES)

    @builtin
    def advance(self, _semantic=None):
        """Make the tile requested by ``try_cancel`` the current tile.

        Waits the "full" barrier, loads the CLC response, and refreshes validity;
        returns the updated scheduler.
        """
        b = _semantic.builder
        one = b.get_int32(1)
        phase = b.create_and(self._iter.handle, one)
        resp = self._responses.handle  # depth == 1: single slot
        bar = self._barriers.handle
        b.create_clc_barrier_wait(bar, phase)
        result = b.create_clc_load_result(resp)
        valid = b.create_clc_is_canceled(result)
        next_iter = b.create_add(self._iter.handle, one)
        return ClcTileScheduler(
            tl.tensor(valid, tl.int1),
            _opaque_value(result),
            tl.tensor(next_iter, tl.int32),
            self._responses,
            self._barriers,
            self._depth,
        )


# `@_aggregate` only transfers methods (not properties) onto the value class, so
# attach the `tile_id` accessor property here.
ClcTileScheduler.tile_id = property(lambda self: _tile_id_accessor(self))


@builtin
def clc_tile_scheduler(_semantic=None):
    """Create a CLC tile scheduler for a dynamic persistent kernel (Blackwell).

    The current tile is seeded from the static launch coordinate so the first
    iteration has work with no CLC round-trip. Prefetch depth is taken from
    ``TRITON_WS_TILE_PREFETCH_DEPTH`` (``knobs.nvidia.ws_tile_prefetch_depth``).
    """
    depth = int(knobs.nvidia.ws_tile_prefetch_depth)
    if depth != 1:
        raise ValueError("tl.clc_tile_scheduler currently supports TRITON_WS_TILE_PREFETCH_DEPTH=1 only "
                         f"(deeper prefetch needs drain-on-exit); got {depth}")
    b = _semantic.builder
    responses = _opaque_value(b.create_clc_alloc_response())
    barriers = _opaque_value(b.create_clc_alloc_barriers(depth))
    clc_result = _opaque_value(b.create_clc_null_result())
    valid = tl.tensor(b.get_int1(True), tl.int1)
    it = tl.tensor(b.get_int32(0), tl.int32)
    return ClcTileScheduler(valid, clc_result, it, responses, barriers, constexpr(depth))
