// RUN: split-file %s %t
// RUN: triton-opt %t/assignment.mlir -split-input-file -allow-unregistered-dialect --nvws-insert-semas=num-stages=2 --nvws-assign-semaphore-stage-phase -cse | FileCheck %t/assignment.mlir --check-prefix=ASP
// RUN: triton-opt %t/assignment.mlir -split-input-file -allow-unregistered-dialect --nvws-insert-semas=num-stages=2 --nvws-semaphore-optimize=num-stages=2 --nvws-assign-semaphore-stage-phase -cse | FileCheck %t/assignment.mlir --check-prefix=ASP
// RUN: triton-opt %t/lowering.mlir -split-input-file -allow-unregistered-dialect --nvws-insert-semas=num-stages=2 --nvws-semaphore-optimize=num-stages=2 --nvws-assign-semaphore-stage-phase --nvws-lower-semaphore=num-stages=2 -cse | FileCheck %t/lowering.mlir --check-prefix=LOWER --implicit-check-not=nvws.descriptor_load
// RUN: triton-opt %t/completion.mlir -split-input-file -allow-unregistered-dialect --nvws-insert-semas=num-stages=2 --nvws-semaphore-optimize=num-stages=2 --nvws-assign-semaphore-stage-phase --nvws-lower-semaphore=num-stages=2 --triton-nvidia-tma-lowering --verify-each=false -cse | FileCheck %t/completion.mlir --check-prefix=TMA
// RUN: triton-opt %t/startup.mlir -split-input-file -allow-unregistered-dialect --nvws-insert-semas=num-stages=2 --nvws-semaphore-optimize=num-stages=2 --nvws-assign-semaphore-stage-phase --nvws-lower-semaphore=num-stages=2 --tritongpu-partition-loops --nvws-lower-warp-group --tritongpu-schedule-loops=num-stages=2 --tritongpu-pipeline=num-stages=2 -cse | FileCheck %t/startup.mlir --check-prefix=PIPE
// RUN: triton-opt %t/startup.mlir -split-input-file -allow-unregistered-dialect --nvws-insert-semas='num-stages=2 use-meta-partitioner=true' --nvws-semaphore-optimize=num-stages=2 --nvws-assign-semaphore-stage-phase --nvws-lower-semaphore=num-stages=2 --tritongpu-partition-loops --nvws-lower-warp-group --tritongpu-schedule-loops='num-stages=2 use-meta-ws=true' --tritongpu-pipeline=num-stages=2 -cse | FileCheck %t/startup.mlir --check-prefix=PIPE
// RUN: triton-opt %t/observer.mlir -split-input-file -allow-unregistered-dialect --nvws-insert-semas=num-stages=2 --nvws-semaphore-optimize=num-stages=2 --nvws-assign-semaphore-stage-phase --nvws-lower-semaphore=num-stages=2 -cse | FileCheck %t/observer.mlir --check-prefix=LOWER
// RUN: triton-opt %t/observer.mlir -split-input-file -allow-unregistered-dialect --nvws-insert-semas=num-stages=2 --nvws-semaphore-optimize=num-stages=2 --nvws-assign-semaphore-stage-phase --nvws-lower-semaphore=num-stages=2 --tritongpu-partition-loops | FileCheck %t/observer.mlir --check-prefix=PARTITION

// Focused consumer checks for synchronization generated by InsertSemas.
// Each input appears once and runs only through its relevant downstream passes.

//--- assignment.mlir
// Logical handoffs resolve to physical buffer slots through assignment.

#blocked = #ttg.blocked<{sizePerThread = [1, 128], threadsPerWarp = [32, 1], warpsPerCTA = [4, 1], order = [0, 1]}>
#blocked64 = #ttg.blocked<{sizePerThread = [1, 8], threadsPerWarp = [4, 8], warpsPerCTA = [4, 1], order = [1, 0]}>
#shared = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 16}>
#shared32 = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 32}>
#smem = #ttg.shared_memory
#tmem = #ttng.tensor_memory_encoding<blockM = 128, blockN = 128, colStride = 1>

module attributes {"ttg.num-warps" = 4 : i32, ttg.target = "cuda:100"} {
  // Planner-authored aliases may be different views of one staged backing.
  // Here the smaller member covers the prefix of the larger member.  The
  // read-to-next-write handoff must still target the following physical slot.
  // ASP-LABEL: @fused_partial_alias_depth_three
  tt.func @fused_partial_alias_depth_three(%lb: i32, %ub: i32, %step: i32) {
    // Entry stages 0 and 2 are acquired before their first release; stage 1
    // is released before its first acquire, so the bootstrap mask is 0b101.
    // ASP: [[PLARGE:%.*]] = ttg.local_alloc {buffer.copy = 3 : i32, buffer.id = 502 : i32}
    // ASP: [[PSMALL:%.*]] = ttg.local_alloc {buffer.copy = 3 : i32, buffer.id = 502 : i32}
    // ASP: [[PENTRY:%.*]] = nvws.semaphore.create [[PLARGE]], [[PSMALL]] released = 5 {pending_count = 1 : i32}
    // ASP: [[PFULL0:%.*]] = nvws.semaphore.create [[PLARGE]], [[PSMALL]] {pending_count = 1 : i32}
    // ASP: [[PHANDOFF:%.*]] = nvws.semaphore.create [[PLARGE]], [[PSMALL]] {pending_count = 1 : i32}
    // ASP: [[PFULL1:%.*]] = nvws.semaphore.create [[PLARGE]], [[PSMALL]] {pending_count = 1 : i32}
    %large = ttg.local_alloc {buffer.copy = 3 : i32, buffer.id = 502 : i32} : () -> !ttg.memdesc<256x64xf16, #shared, #smem, mutable>
    %small = ttg.local_alloc {buffer.copy = 3 : i32, buffer.id = 502 : i32} : () -> !ttg.memdesc<128x64xf16, #shared, #smem, mutable>
    %small_value = arith.constant dense<0.000000e+00> : tensor<128x64xf16, #blocked64>
    %large_value = arith.constant dense<1.000000e+00> : tensor<256x64xf16, #blocked64>
    // ASP: scf.for
    scf.for %iv = %lb to %ub step %step : i32 {
      // Small-member write: acquire PENTRY, store through view #1 (the small
      // member), release PFULL0.
      // ASP: [[PSLOT0:%.*]] = arith.select {{%.*}}, {{%.*}}, {{%.*}} {ttg.partition = array<i32: 2, 4>} : i32
      // ASP: [[PW0_TOK:%.*]] = nvws.semaphore.acquire [[PENTRY]][[[PSLOT0]], {{%.*}}] {ttg.partition = array<i32: 4>}
      // ASP: [[PW0_BUF:%.*]]:2 = nvws.semaphore.buffer [[PENTRY]][[[PSLOT0]]], [[PW0_TOK]] {ttg.partition = array<i32: 4>}
      // ASP: ttg.local_store {{%.*}}, [[PW0_BUF]]#1 {ttg.partition = array<i32: 4>}
      // ASP: nvws.semaphore.release [[PFULL0]][[[PSLOT0]]], [[PW0_TOK]] [#nvws.async_op<none>] {arrive_count = 1 : i32, ttg.partition = array<i32: 4>}
      ttg.local_store %small_value, %small {ttg.partition = array<i32: 4>} : tensor<128x64xf16, #blocked64> -> !ttg.memdesc<128x64xf16, #shared, #smem, mutable>
      // Small-member read: acquire PFULL0, load view #1, then hand off to the
      // large write at the following physical slot (PSLOT0 + 1) mod 3.
      // ASP: [[PR0_TOK:%.*]] = nvws.semaphore.acquire [[PFULL0]][[[PSLOT0]], {{%.*}}] {ttg.partition = array<i32: 2>}
      // ASP: [[PR0_BUF:%.*]]:2 = nvws.semaphore.buffer [[PFULL0]][[[PSLOT0]]], [[PR0_TOK]] {ttg.partition = array<i32: 2>}
      // ASP: ttg.local_load [[PR0_BUF]]#1 {ttg.partition = array<i32: 2>}
      // ASP: [[TO_LARGE_RAW:%.*]] = arith.addi [[PSLOT0]], {{%.*}} {ttg.partition = array<i32: 2>} : i32
      // ASP: [[TO_LARGE_REM:%.*]] = arith.remsi [[TO_LARGE_RAW]], {{%.*}} {ttg.partition = array<i32: 2>} : i32
      // ASP: [[TO_LARGE_SLOT:%.*]] = arith.select {{%.*}}, {{%.*}}, [[TO_LARGE_REM]] {ttg.partition = array<i32: 2>} : i32
      // ASP: nvws.semaphore.release [[PHANDOFF]][[[TO_LARGE_SLOT]]], [[PR0_TOK]] [#nvws.async_op<none>] {arrive_count = 1 : i32, ttg.partition = array<i32: 2>}
      %small_read = ttg.local_load %small {ttg.partition = array<i32: 2>} : !ttg.memdesc<128x64xf16, #shared, #smem, mutable> -> tensor<128x64xf16, #blocked64>
      "consume_small"(%small_read) {ttg.partition = array<i32: 2>} : (tensor<128x64xf16, #blocked64>) -> ()
      // Large-member write: acquire PHANDOFF at the successor slot, store
      // through view #0 (the large member), release PFULL1.
      // ASP: [[PSLOT1_RAW:%.*]] = arith.addi [[PSLOT0]], {{%.*}} {ttg.partition = array<i32: 2, 4>} : i32
      // ASP: [[PSLOT1:%.*]] = arith.select {{%.*}}, {{%.*}}, [[PSLOT1_RAW]] {ttg.partition = array<i32: 2, 4>} : i32
      // ASP: [[PW1_TOK:%.*]] = nvws.semaphore.acquire [[PHANDOFF]][[[PSLOT1]], {{%.*}}] {ttg.partition = array<i32: 4>}
      // ASP: [[PW1_BUF:%.*]]:2 = nvws.semaphore.buffer [[PHANDOFF]][[[PSLOT1]]], [[PW1_TOK]] {ttg.partition = array<i32: 4>}
      // ASP: ttg.local_store {{%.*}}, [[PW1_BUF]]#0 {ttg.partition = array<i32: 4>}
      // ASP: nvws.semaphore.release [[PFULL1]][[[PSLOT1]]], [[PW1_TOK]] [#nvws.async_op<none>] {arrive_count = 1 : i32, ttg.partition = array<i32: 4>}
      ttg.local_store %large_value, %large {ttg.partition = array<i32: 4>} : tensor<256x64xf16, #blocked64> -> !ttg.memdesc<256x64xf16, #shared, #smem, mutable>
      // Large-member read: acquire PFULL1, load view #0, close the loop by
      // releasing PENTRY at the reader's own slot (constant 0 / PSLOT1: the
      // slot the next small write reaches two iterations later).
      // ASP: [[PR1_TOK:%.*]] = nvws.semaphore.acquire [[PFULL1]][[[PSLOT1]], {{%.*}}] {ttg.partition = array<i32: 2>}
      // ASP: [[PR1_BUF:%.*]]:2 = nvws.semaphore.buffer [[PFULL1]][[[PSLOT1]]], [[PR1_TOK]] {ttg.partition = array<i32: 2>}
      // ASP: ttg.local_load [[PR1_BUF]]#0 {ttg.partition = array<i32: 2>}
      // ASP: nvws.semaphore.release [[PENTRY]][[[PSLOT1]]], [[PR1_TOK]] [#nvws.async_op<none>] {arrive_count = 1 : i32, ttg.partition = array<i32: 2>}
      // ASP: scf.yield {ttg.partition = array<i32: 2, 4>} [[PSLOT1]],
      %large_read = ttg.local_load %large {ttg.partition = array<i32: 2>} : !ttg.memdesc<256x64xf16, #shared, #smem, mutable> -> tensor<256x64xf16, #blocked64>
      "consume_large"(%large_read) {ttg.partition = array<i32: 2>} : (tensor<256x64xf16, #blocked64>) -> ()
    } {tt.warp_specialize, ttg.partition = array<i32: 2, 4>, ttg.partition.outputs = [], ttg.warp_specialize.tag = 2 : i32}
    tt.return
  }
}

// -----

#blocked = #ttg.blocked<{sizePerThread = [1, 128], threadsPerWarp = [32, 1], warpsPerCTA = [4, 1], order = [0, 1]}>
#blocked64 = #ttg.blocked<{sizePerThread = [1, 8], threadsPerWarp = [4, 8], warpsPerCTA = [4, 1], order = [1, 0]}>
#shared = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 16}>
#shared32 = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 32}>
#smem = #ttg.shared_memory
#tmem = #ttng.tensor_memory_encoding<blockM = 128, blockN = 128, colStride = 1>

module attributes {"ttg.num-warps" = 4 : i32, ttg.target = "cuda:100"} {
  // C: the loop-exit relay reserves the successor slot for the next W0.
  // ASP-LABEL: @case_c
  tt.func @case_c(%lb: i32, %ub: i32, %step: i32,
                  %lhs: !ttg.memdesc<128x64xf32, #shared32, #smem>,
                  %rhs: !ttg.memdesc<64x128xf32, #shared32, #smem>) {
    %true = arith.constant true
    %false = arith.constant false
    %zero = arith.constant dense<0.0> : tensor<128x128xf32, #blocked>
    // ASP: [[C_BASE:%.*]] = ttng.tmem_alloc {buffer.copy = 3 : i32}
    // ASP: [[C_ENTRY:%.*]] = nvws.semaphore.create [[C_BASE]] released = 1 {pending_count = 1 : i32}
    // ASP: [[C_FULL:%.*]] = nvws.semaphore.create [[C_BASE]] {pending_count = 1 : i32}
    // ASP: [[C_FREE:%.*]] = nvws.semaphore.create [[C_BASE]] released = 6 {pending_count = 1 : i32}
    %acc, %tok = ttng.tmem_alloc {buffer.copy = 3 : i32} : () -> (!ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable>, !ttg.async.token)
    // ASP: scf.for {{.*}} iter_args([[C_OUTER_CURRENT_STAGE:%[-A-Za-z0-9_.$#]+]] = {{%[-A-Za-z0-9_.$#]+}},
    %outer = scf.for %i = %lb to %ub step %step iter_args(%outer_token = %tok) -> (!ttg.async.token) : i32 {
      // ASP: [[C_ONE:%.*]] = arith.constant {ttg.partition = array<i32: 0, 1>} 1 : i32
      // ASP: [[C_OUTER_NEXT_RAW:%.*]] = arith.addi [[C_OUTER_CURRENT_STAGE]], [[C_ONE]] {ttg.partition = array<i32: 0, 1>} : i32
      // ASP: [[C_DEPTH:%.*]] = arith.constant {ttg.partition = array<i32: 0, 1>} 3 : i32
      // ASP: [[C_OUTER_NEEDS_WRAP:%.*]] = arith.cmpi eq, [[C_OUTER_NEXT_RAW]], [[C_DEPTH]] {ttg.partition = array<i32: 0, 1>} : i32
      // ASP: [[C_ZERO:%.*]] = arith.constant {ttg.partition = array<i32: 0, 1>} 0 : i32
      // ASP: [[C_NEXT_OF_OUTER_STAGE:%.*]] = arith.select [[C_OUTER_NEEDS_WRAP]], [[C_ZERO]], [[C_OUTER_NEXT_RAW]] {ttg.partition = array<i32: 0, 1>} : i32
      // ASP: [[C_W0_TOK:%.*]] = nvws.semaphore.acquire [[C_ENTRY]][[[C_NEXT_OF_OUTER_STAGE]], {{%.*}}] {ttg.partition = array<i32: 0>}
      // ASP: [[C_W0_BUF:%.*]] = nvws.semaphore.buffer [[C_ENTRY]][[[C_NEXT_OF_OUTER_STAGE]]], [[C_W0_TOK]] {ttg.partition = array<i32: 0>}
      // ASP: ttng.tmem_store {{%.*}}, [[C_W0_BUF]][], {{%.*}} {ttg.partition = array<i32: 0>}
      // ASP: nvws.semaphore.release [[C_FREE]][[[C_NEXT_OF_OUTER_STAGE]]], [[C_W0_TOK]] [#nvws.async_op<none>] {arrive_count = 1 : i32, ttg.partition = array<i32: 0>}
      %w0 = ttng.tmem_store %zero, %acc[%outer_token], %true {ttg.partition = array<i32: 0>} : tensor<128x128xf32, #blocked> -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable>
      // ASP: [[C_INNER_LOOP:%.*]]:3 = scf.for {{.*}} iter_args([[C_INNER_CURRENT_STAGE:%[-A-Za-z0-9_.$#]+]] = [[C_NEXT_OF_OUTER_STAGE]],
      %inner = scf.for %j = %lb to %ub step %step iter_args(%inner_token = %w0) -> (!ttg.async.token) : i32 {
        // ASP: [[C_INNER_NEXT_RAW:%.*]] = arith.addi [[C_INNER_CURRENT_STAGE]], [[C_ONE]] {ttg.partition = array<i32: 0, 1>} : i32
        // ASP: [[C_INNER_NEEDS_WRAP:%.*]] = arith.cmpi eq, [[C_INNER_NEXT_RAW]], [[C_DEPTH]] {ttg.partition = array<i32: 0, 1>} : i32
        // ASP: [[C_NEXT_OF_INNER_CURRENT_STAGE:%.*]] = arith.select [[C_INNER_NEEDS_WRAP]], [[C_ZERO]], [[C_INNER_NEXT_RAW]] {ttg.partition = array<i32: 0, 1>} : i32
        // ASP: [[C_W1_TOK:%.*]] = nvws.semaphore.acquire [[C_FREE]][[[C_NEXT_OF_INNER_CURRENT_STAGE]], {{%.*}}] {ttg.partition = array<i32: 1>}
        // ASP: [[C_W1_BUF:%.*]] = nvws.semaphore.buffer [[C_FREE]][[[C_NEXT_OF_INNER_CURRENT_STAGE]]], [[C_W1_TOK]] {ttg.partition = array<i32: 1>}
        // ASP: ttng.tc_gen5_mma {{%.*}}, {{%.*}}, [[C_W1_BUF]][], {{%.*}}, {{%.*}} {ttg.partition = array<i32: 1>}
        // ASP: nvws.semaphore.release [[C_FULL]][[[C_NEXT_OF_INNER_CURRENT_STAGE]]], [[C_W1_TOK]] [#nvws.async_op<tc5mma>] {arrive_count = 1 : i32, ttg.partition = array<i32: 1>}
        %w1 = ttng.tc_gen5_mma %lhs, %rhs, %acc[%inner_token], %false, %true {ttg.partition = array<i32: 1>} : !ttg.memdesc<128x64xf32, #shared32, #smem>, !ttg.memdesc<64x128xf32, #shared32, #smem>, !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable>
        // ASP: [[C_READ_TOK:%.*]] = nvws.semaphore.acquire [[C_FULL]][[[C_NEXT_OF_INNER_CURRENT_STAGE]], {{%.*}}] {ttg.partition = array<i32: 0>}
        // ASP: [[C_READ_BUF:%.*]] = nvws.semaphore.buffer [[C_FULL]][[[C_NEXT_OF_INNER_CURRENT_STAGE]]], [[C_READ_TOK]] {ttg.partition = array<i32: 0>}
        // ASP: {{%.*}}, {{%.*}} = ttng.tmem_load [[C_READ_BUF]][] {ttg.partition = array<i32: 0>}
        // ASP: nvws.semaphore.release [[C_FREE]][[[C_NEXT_OF_INNER_CURRENT_STAGE]]], [[C_READ_TOK]] [#nvws.async_op<none>] {arrive_count = 1 : i32, ttg.partition = array<i32: 0>}
        %value, %read = ttng.tmem_load %acc[%w1] {ttg.partition = array<i32: 0>} : !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable> -> tensor<128x128xf32, #blocked>
        "use_c"(%value) {ttg.partition = array<i32: 0>} : (tensor<128x128xf32, #blocked>) -> ()
        scf.yield {ttg.partition = array<i32: 0, 1>} %read : !ttg.async.token
      } {ttg.partition = array<i32: 0, 1>, ttg.partition.outputs = [array<i32: 0>]}
      // The accessless relay targets next(inner-stage) on both sides.
      // ASP: [[C_NEXT_OF_INNER_RAW:%.*]] = arith.addi [[C_INNER_LOOP]]#0, [[C_ONE]] {ttg.partition = array<i32: 0, 1>} : i32
      // ASP: [[C_NEXT_OF_INNER_REM:%.*]] = arith.remsi [[C_NEXT_OF_INNER_RAW]], [[C_DEPTH]] {ttg.partition = array<i32: 0, 1>} : i32
      // ASP: [[C_NEXT_OF_INNER_STAGE:%.*]] = arith.select {{.*}}, {{.*}}, [[C_NEXT_OF_INNER_REM]] {ttg.partition = array<i32: 0, 1>} : i32
      // ASP: [[C_REL_ONE:%.*]] = arith.constant {ttg.partition = array<i32: 1>} 1 : i32
      // ASP: [[C_EXIT_TOK:%.*]] = nvws.semaphore.acquire [[C_FREE]][[[C_NEXT_OF_INNER_STAGE]], {{%.*}}] {ttg.partition = array<i32: 1>}
      // ASP: [[C_RELEASE_NEXT_OF_INNER_RAW:%.*]] = arith.addi [[C_INNER_LOOP]]#0, [[C_REL_ONE]] {ttg.partition = array<i32: 1>} : i32
      // ASP: [[C_REL_DEPTH:%.*]] = arith.constant {ttg.partition = array<i32: 1>} 3 : i32
      // ASP: [[C_RELEASE_NEXT_OF_INNER_REM:%.*]] = arith.remsi [[C_RELEASE_NEXT_OF_INNER_RAW]], [[C_REL_DEPTH]] {ttg.partition = array<i32: 1>} : i32
      // ASP: [[C_RELEASE_NEXT_OF_INNER_STAGE:%.*]] = arith.select {{.*}}, {{.*}}, [[C_RELEASE_NEXT_OF_INNER_REM]] {ttg.partition = array<i32: 1>} : i32
      // ASP: nvws.semaphore.release [[C_ENTRY]][[[C_RELEASE_NEXT_OF_INNER_STAGE]]], [[C_EXIT_TOK]] [#nvws.async_op<none>] {arrive_count = 1 : i32, ttg.partition = array<i32: 1>}
      scf.yield {ttg.partition = array<i32: 0, 1>} %inner : !ttg.async.token
    } {tt.warp_specialize, ttg.partition = array<i32: 0, 1>, ttg.partition.outputs = [array<i32: 0>], ttg.warp_specialize.tag = 12 : i32}
    tt.return
  }
}

//--- lowering.mlir
#reg1 = #ttg.blocked<{sizePerThread = [1], threadsPerWarp = [32], warpsPerCTA = [4], order = [0]}>
#shared1 = #ttg.swizzled_shared<{vec = 1, perPhase = 1, maxPhase = 1, order = [0]}>
#reg = #ttg.blocked<{sizePerThread = [1, 128], threadsPerWarp = [32, 1], warpsPerCTA = [4, 1], order = [0, 1]}>
#shared = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 16}>
#tmem = #ttng.tensor_memory_encoding<blockM = 128, blockN = 128, colStride = 1>
#smem = #ttg.shared_memory
#tm = #ttng.tensor_memory
!acc = !ttg.memdesc<128x128xf32, #tmem, #tm, mutable>
!tile = tensor<128x128xf32, #reg>
!lhs = !ttg.memdesc<128x64xf16, #shared, #smem>
!rhs = !ttg.memdesc<64x128xf16, #shared, #smem>

module attributes {"ttg.num-warps" = 4 : i32, ttg.target = "cuda:100"} {
  // LOWER-LABEL: @smem_nested_fanin
  // LOWER: [[FANIN_STORAGE:%.*]] = ttg.local_alloc : () -> !ttg.memdesc<1x1xi64,
  // LOWER: ttng.init_barrier {{.*}}, 2
  // LOWER: scf.for
  // LOWER: [[FANIN_RELAY:%.*]] = ttg.memdesc_index [[FANIN_STORAGE]][
  // LOWER: ttng.arrive_barrier [[FANIN_RELAY]], 2
  // LOWER-NEXT: scf.for
  // LOWER: ttng.wait_barrier
  // LOWER: ttg.local_load
  tt.func @smem_nested_fanin(%value: tensor<1xi32, #reg1>) {
    %c0 = arith.constant 0 : i32
    %c1 = arith.constant 1 : i32
    %c2 = arith.constant 2 : i32
    %buffer = ttg.local_alloc {buffer.copy = 1 : i32, buffer.id = 102 : i32} : () -> !ttg.memdesc<1xi32, #shared1, #smem, mutable>
    ttg.local_store %value, %buffer {ttg.partition = array<i32: 2>, ttg.warp_specialize.tag = 0 : i32} : tensor<1xi32, #reg1> -> !ttg.memdesc<1xi32, #shared1, #smem, mutable>
    scf.for %i = %c0 to %c2 step %c1 : i32 {
      // The incoming permit supplies two arrivals for the two independent completions.
      scf.for %j = %c0 to %c2 step %c1 : i32 {
        %first = ttg.local_load %buffer {ttg.partition = array<i32: 2>} : !ttg.memdesc<1xi32, #shared1, #smem, mutable> -> tensor<1xi32, #reg1>
        "consume_first"(%first) {ttg.partition = array<i32: 2>} : (tensor<1xi32, #reg1>) -> ()
        %second = ttg.local_load %buffer {ttg.partition = array<i32: 1>} : !ttg.memdesc<1xi32, #shared1, #smem, mutable> -> tensor<1xi32, #reg1>
        %corrected = arith.addi %second, %second {ttg.partition = array<i32: 1>} : tensor<1xi32, #reg1>
        ttg.local_store %corrected, %buffer {ttg.partition = array<i32: 1>} : tensor<1xi32, #reg1> -> !ttg.memdesc<1xi32, #shared1, #smem, mutable>
        %last = ttg.local_load %buffer {ttg.partition = array<i32: 0>} : !ttg.memdesc<1xi32, #shared1, #smem, mutable> -> tensor<1xi32, #reg1>
        "consume_last"(%last) {ttg.partition = array<i32: 0>} : (tensor<1xi32, #reg1>) -> ()
      } {ttg.partition = array<i32: 0, 1, 2>}
      %after = ttg.local_load %buffer {ttg.partition = array<i32: 2>} : !ttg.memdesc<1xi32, #shared1, #smem, mutable> -> tensor<1xi32, #reg1>
      "consume_final"(%after) {ttg.partition = array<i32: 2>} : (tensor<1xi32, #reg1>) -> ()
    } {tt.warp_specialize, ttg.partition = array<i32: 0, 1, 2>, ttg.partition.stages = [0 : i32, 0 : i32, 0 : i32], ttg.warp_specialize.tag = 0 : i32}
    tt.return
  }
}

// -----

// Native num-stages=2 capture from python/test/unit/language/test_warp_specialization.py.
// Debug locations are removed; input operations are unchanged.
#blocked = #ttg.blocked<{sizePerThread = [1], threadsPerWarp = [32], warpsPerCTA = [4], order = [0]}>
#blocked1 = #ttg.blocked<{sizePerThread = [1, 8], threadsPerWarp = [2, 16], warpsPerCTA = [4, 1], order = [1, 0]}>
#linear = #ttg.linear<{register = [[0, 1], [0, 2], [0, 4], [0, 8], [0, 16], [0, 32], [0, 64]], lane = [[1, 0], [2, 0], [4, 0], [8, 0], [16, 0]], warp = [[32, 0], [64, 0]], block = []}>
#shared = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 16}>
#shared1 = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = true, elementBitWidth = 16}>
#smem = #ttg.shared_memory
#tmem = #ttng.tensor_memory_encoding<blockM = 128, blockN = 128, colStride = 1>
module attributes {"ttg.cluster-dim-x" = 1 : i32, "ttg.cluster-dim-y" = 1 : i32, "ttg.cluster-dim-z" = 1 : i32, ttg.early_tma_store_lowering = true, ttg.min_reg_auto_ws = 24 : i32, "ttg.num-ctas" = 1 : i32, "ttg.num-warps" = 4 : i32, ttg.target = "cuda:100", "ttg.threads-per-warp" = 32 : i32} {
  // LOWER-LABEL: @attention_persistent_inner_loop_kernel(
  // LOWER-SAME: [[CAP_Q:%[-A-Za-z0-9_.$#]+]]: !tt.tensordesc
  // LOWER-SAME: [[CAP_K:%[-A-Za-z0-9_.$#]+]]: !tt.tensordesc
  // LOWER-SAME: [[CAP_V:%[-A-Za-z0-9_.$#]+]]: !tt.tensordesc
  // LOWER-SAME: [[CAP_O:%[-A-Za-z0-9_.$#]+]]: !tt.tensordesc
  tt.func public @attention_persistent_inner_loop_kernel(
      %desc_q: !tt.tensordesc<128x128xf16, #shared>,
      %desc_q.shape.0: i32,
      %desc_q.shape.1: i32,
      %desc_q.stride.0: i64,
      %desc_q.stride.1: i64,
      %desc_k: !tt.tensordesc<128x128xf16, #shared>,
      %desc_k.shape.0: i32,
      %desc_k.shape.1: i32,
      %desc_k.stride.0: i64,
      %desc_k.stride.1: i64,
      %desc_v: !tt.tensordesc<128x128xf16, #shared>,
      %desc_v.shape.0: i32,
      %desc_v.shape.1: i32,
      %desc_v.stride.0: i64,
      %desc_v.stride.1: i64,
      %desc_acc: !tt.tensordesc<128x128xf16, #shared>,
      %desc_acc.shape.0: i32,
      %desc_acc.shape.1: i32,
      %desc_acc.stride.0: i64,
      %desc_acc.stride.1: i64,
      %l_i_ptr: !tt.ptr<f16> {tt.divisibility = 16 : i32},
      %m_i_ptr: !tt.ptr<f16> {tt.divisibility = 16 : i32},
      %M: i32 {tt.divisibility = 16 : i32},
      %N: i32 {tt.divisibility = 16 : i32},
      %qk_scale: f32) attributes {noinline = false} {
    %false = arith.constant false
    %true = arith.constant true
    %c1_i32 = arith.constant 1 : i32
    %c0_i32 = arith.constant 0 : i32
    %c128_i32 = arith.constant 128 : i32
    %num_tiles = arith.constant 127 : i32
    %cst = arith.constant dense<1.000000e+00> : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
    %cst_0 = arith.constant dense<0xFF800000> : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
    %cst_1 = arith.constant dense<0.000000e+00> : tensor<128x128xf32, #linear>
    %prog_id = tt.get_program_id x : i32
    %num_sm = tt.get_num_programs x : i32
    %num_tiles_2 = arith.addi %M, %num_tiles : i32
    %num_tiles_3 = arith.divsi %num_tiles_2, %c128_i32 : i32
    %tiles_per_sm = arith.divsi %num_tiles_3, %num_sm : i32
    %0 = arith.remsi %num_tiles_3, %num_sm : i32
    %1 = arith.cmpi slt, %prog_id, %0 : i32
    %2 = scf.if %1 -> (i32) {
      %tiles_per_sm_6 = arith.addi %tiles_per_sm, %c1_i32 : i32
      scf.yield %tiles_per_sm_6 : i32
    } else {
      scf.yield %tiles_per_sm : i32
    }
    %m_ij = tt.splat %qk_scale : f32 -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
    %qk = tt.splat %qk_scale : f32 -> tensor<128x128xf32, #linear>
    %3 = tt.make_range {end = 128 : i32, start = 0 : i32} : tensor<128xi32, #blocked>
    // The initialized accumulator owns one slot; its permit crosses outer trips.
    // LOWER: [[CAP_LACC:%.*]] = ttng.tmem_alloc : () -> !ttg.memdesc<1x128x128xf32,
    // LOWER-NEXT: [[CAP_BARRIER:%.*]] = ttg.local_alloc : () -> !ttg.memdesc<1x1xi64,
    // LOWER-NEXT: [[CAP_INITIAL_BARRIER:%.*]] = ttg.memdesc_index [[CAP_BARRIER]][
    // LOWER-NEXT: ttng.init_barrier [[CAP_INITIAL_BARRIER]], 1
    %acc = ttng.tmem_alloc : () -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable>
    %acc_4 = ub.poison : !ttg.async.token
    %acc_5 = ttng.tmem_alloc : () -> !ttg.memdesc<128x128xf16, #tmem, #ttng.tensor_memory, mutable>
    %q = ttg.local_alloc : () -> !ttg.memdesc<128x128xf16, #shared, #smem, mutable>
    %k = ttg.local_alloc : () -> !ttg.memdesc<128x128xf16, #shared, #smem, mutable>
    %v = ttg.local_alloc : () -> !ttg.memdesc<128x128xf16, #shared, #smem, mutable>
    // LOWER: scf.for
    %tile_idx = scf.for %_ = %c0_i32 to %2 step %c1_i32 iter_args(%tile_idx_6 = %prog_id) -> (i32)  : i32 {
      %off_m = arith.muli %tile_idx_6, %c128_i32 {ttg.partition = array<i32: 0, 2>} : i32
      // LOWER: ttng.async_tma_copy_global_to_local [[CAP_Q]]{{.*}} {ttg.partition = array<i32: 2>}
      nvws.descriptor_load %desc_q[%off_m, %c0_i32] 32768 %q {multicast = false, ttg.partition = array<i32: 2>} : !tt.tensordesc<128x128xf16, #shared>, i32, i32, !ttg.memdesc<128x128xf16, #shared, #smem, mutable>
      %qk_7, %qk_8 = ttng.tmem_alloc {ttg.partition = array<i32: 0, 1>} : () -> (!ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable>, !ttg.async.token)
      %acc_9 = arith.constant {ttg.partition = array<i32: 0>} true
      // LOWER: [[CAP_LINIT_BUF:%.*]] = ttg.memdesc_index [[CAP_LACC]][[[CAP_LSLOT:%.*]]]
      // LOWER-NEXT: ttng.tmem_store {{%.*}}, [[CAP_LINIT_BUF]],
      // LOWER-NEXT: [[CAP_RELAY:%.*]] = ttg.memdesc_index [[CAP_BARRIER]][[[CAP_LSLOT]]]
      // LOWER-NEXT: ttng.arrive_barrier [[CAP_RELAY]], 1 {ttg.partition = array<i32: 0>}
      ttng.tmem_store %cst_1, %acc, %acc_9 {ttg.partition = array<i32: 0>} : tensor<128x128xf32, #linear> -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable>
      // LOWER: [[CAP_LINNER:%[-A-Za-z0-9_.$#]+]]:{{[0-9]+}} = scf.for
      %acc_10:5 = scf.for %start_n = %c0_i32 to %N step %c128_i32 iter_args(%m_i = %cst_0, %l_i = %cst, %acc_14 = %false, %qk_15 = %qk_8, %acc_16 = %acc_4) -> (tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>, tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>, i1, !ttg.async.token, !ttg.async.token)  : i32 {
        // LOWER: ttng.async_tma_copy_global_to_local [[CAP_K]]{{.*}} {loop.cluster = 3 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 2>}
        nvws.descriptor_load %desc_k[%start_n, %c0_i32] 32768 %k {loop.cluster = 3 : i32, loop.stage = 0 : i32, multicast = false, ttg.partition = array<i32: 2>} : !tt.tensordesc<128x128xf16, #shared>, i32, i32, !ttg.memdesc<128x128xf16, #shared, #smem, mutable>
        %k_17 = ttg.memdesc_trans %k {loop.cluster = 2 : i32, loop.stage = 1 : i32, order = array<i32: 1, 0>, ttg.partition = array<i32: 1>} : !ttg.memdesc<128x128xf16, #shared, #smem, mutable> -> !ttg.memdesc<128x128xf16, #shared1, #smem, mutable>
        %qk_18 = ttng.tc_gen5_mma %q, %k_17, %qk_7[%qk_15], %false, %true {loop.cluster = 2 : i32, loop.stage = 1 : i32, tt.self_latency = 0 : i32, ttg.partition = array<i32: 1>} : !ttg.memdesc<128x128xf16, #shared, #smem, mutable>, !ttg.memdesc<128x128xf16, #shared1, #smem, mutable>, !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable>
        %qk_19, %qk_20 = ttng.tmem_load %qk_7[%qk_18] {loop.cluster = 0 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>} : !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable> -> tensor<128x128xf32, #linear>
        %m_ij_21 = "tt.reduce"(%qk_19) <{axis = 1 : i32, reduction_ordering = "unordered"}> ({
        ^bb0(%m_ij_40: f32, %m_ij_41: f32):
          %m_ij_42 = arith.maxnumf %m_ij_40, %m_ij_41 {ttg.partition = array<i32: 0>} : f32
          tt.reduce.return %m_ij_42 {ttg.partition = array<i32: 0>} : f32
        }) {loop.cluster = 0 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>, ttg.partition.outputs = [array<i32: 0>]} : (tensor<128x128xf32, #linear>) -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
        %m_ij_22 = arith.mulf %m_ij_21, %m_ij {loop.cluster = 0 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
        %m_ij_23 = arith.maxnumf %m_i, %m_ij_22 {loop.cluster = 0 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
        %qk_24 = arith.mulf %qk_19, %qk {loop.cluster = 0 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>} : tensor<128x128xf32, #linear>
        %qk_25 = tt.expand_dims %m_ij_23 {axis = 1 : i32, loop.cluster = 0 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>> -> tensor<128x1xf32, #linear>
        %qk_26 = tt.broadcast %qk_25 {loop.cluster = 0 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>} : tensor<128x1xf32, #linear> -> tensor<128x128xf32, #linear>
        %qk_27 = arith.subf %qk_24, %qk_26 {loop.cluster = 0 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>} : tensor<128x128xf32, #linear>
        %p = math.exp2 %qk_27 {loop.cluster = 0 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>} : tensor<128x128xf32, #linear>
        %alpha = arith.subf %m_i, %m_ij_23 {loop.cluster = 0 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
        %alpha_28 = math.exp2 %alpha {loop.cluster = 0 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
        %l_ij = "tt.reduce"(%p) <{axis = 1 : i32, reduction_ordering = "unordered"}> ({
        ^bb0(%l_ij_40: f32, %l_ij_41: f32):
          %l_ij_42 = arith.addf %l_ij_40, %l_ij_41 {ttg.partition = array<i32: 0>} : f32
          tt.reduce.return %l_ij_42 {ttg.partition = array<i32: 0>} : f32
        }) {loop.cluster = 0 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>, ttg.partition.outputs = [array<i32: 0>]} : (tensor<128x128xf32, #linear>) -> tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
        %acc_29 = tt.expand_dims %alpha_28 {axis = 1 : i32, loop.cluster = 0 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>> -> tensor<128x1xf32, #linear>
        %acc_30 = tt.broadcast %acc_29 {loop.cluster = 0 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>} : tensor<128x1xf32, #linear> -> tensor<128x128xf32, #linear>
        // Correction consumes the relayed permit and the same accumulator view.
        // LOWER: [[CAP_INNER_WAIT:%.*]] = ttg.memdesc_index [[CAP_BARRIER]][[[CAP_CORRECT_SLOT:%.*]]]
        // LOWER-NEXT: ttng.wait_barrier [[CAP_INNER_WAIT]], {{%.*}} {loop.cluster = 0 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>}
        // LOWER-NEXT: [[CAP_CORRECT_BUF:%.*]] = ttg.memdesc_index [[CAP_LACC]][[[CAP_CORRECT_SLOT]]]
        // LOWER-NEXT: {{%.*}}, {{%.*}} = ttng.tmem_load [[CAP_CORRECT_BUF]][]
        %acc_31, %acc_32 = ttng.tmem_load %acc[%acc_16] {loop.cluster = 0 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>} : !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable> -> tensor<128x128xf32, #linear>
        %acc_33 = arith.mulf %acc_31, %acc_30 {loop.cluster = 0 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>} : tensor<128x128xf32, #linear>
        // LOWER: ttng.async_tma_copy_global_to_local [[CAP_V]]{{.*}} {loop.cluster = 1 : i32, loop.stage = 2 : i32, ttg.partition = array<i32: 2>}
        nvws.descriptor_load %desc_v[%start_n, %c0_i32] 32768 %v {loop.cluster = 1 : i32, loop.stage = 2 : i32, multicast = false, ttg.partition = array<i32: 2>} : !tt.tensordesc<128x128xf16, #shared>, i32, i32, !ttg.memdesc<128x128xf16, #shared, #smem, mutable>
        %p_34 = arith.truncf %p {loop.cluster = 0 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>} : tensor<128x128xf32, #linear> to tensor<128x128xf16, #linear>
        %acc_35 = arith.constant {loop.cluster = 0 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>} true
        ttng.tmem_store %p_34, %acc_5, %acc_35 {loop.cluster = 0 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>} : tensor<128x128xf16, #linear> -> !ttg.memdesc<128x128xf16, #tmem, #ttng.tensor_memory, mutable>
        %acc_36 = ttng.tmem_store %acc_33, %acc[%acc_32], %true {loop.cluster = 0 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>} : tensor<128x128xf32, #linear> -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable>
        // LOWER: ttng.tc_gen5_mma {{.*}} {is_async, loop.cluster = 0 : i32, loop.stage = 3 : i32,
        // LOWER: [[CAP_COMMIT:%.*]] = ttg.memdesc_index [[CAP_BARRIER]][
        // LOWER-NEXT: ttng.tc_gen5_commit [[CAP_COMMIT]] {loop.cluster = 0 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 1>}
        %acc_37 = ttng.tc_gen5_mma %acc_5, %v, %acc[%acc_36], %acc_14, %true {loop.cluster = 0 : i32, loop.stage = 3 : i32, tt.self_latency = 0 : i32, ttg.partition = array<i32: 1>} : !ttg.memdesc<128x128xf16, #tmem, #ttng.tensor_memory, mutable>, !ttg.memdesc<128x128xf16, #shared, #smem, mutable>, !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable>
        %l_i_38 = arith.mulf %l_i, %alpha_28 {loop.cluster = 0 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
        %l_i_39 = arith.addf %l_i_38, %l_ij {loop.cluster = 0 : i32, loop.stage = 3 : i32, ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>
        scf.yield {ttg.partition = array<i32: 0, 1, 2>} %m_ij_23, %l_i_39, %true, %qk_20, %acc_37 : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>, tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>>, i1, !ttg.async.token, !ttg.async.token
      } {tt.scheduled_max_stage = 3 : i32, ttg.partition = array<i32: 0, 1, 2>, ttg.partition.outputs = [array<i32: 0>, array<i32: 0>, array<i32: 1>, array<i32: 1>, array<i32: 0>]}
      // LOWER: } {tt.scheduled_max_stage = 3 : i32,
      // LOWER: [[CAP_FINAL_WAIT:%.*]] = ttg.memdesc_index [[CAP_BARRIER]][[[CAP_LINNER]]#3]
      // LOWER-NEXT: ttng.wait_barrier [[CAP_FINAL_WAIT]], {{%.*}} {ttg.partition = array<i32: 0>}
      // LOWER-NEXT: [[CAP_LFINAL_BUF:%.*]] = ttg.memdesc_index [[CAP_LACC]][[[CAP_LINNER]]#3]
      // LOWER-NEXT: {{%.*}}, {{%.*}} = ttng.tmem_load [[CAP_LFINAL_BUF]][]
      %acc_11, %acc_12 = ttng.tmem_load %acc[%acc_10#4] {ttg.partition = array<i32: 0>} : !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable> -> tensor<128x128xf32, #linear>
      %4 = arith.truncf %acc_11 {ttg.partition = array<i32: 0>} : tensor<128x128xf32, #linear> to tensor<128x128xf16, #linear>
      %5 = ttg.convert_layout %4 {ttg.partition = array<i32: 0>} : tensor<128x128xf16, #linear> -> tensor<128x128xf16, #blocked1>
      // LOWER: tt.descriptor_store [[CAP_O]][{{.*}}]{{.*}} {ttg.partition = array<i32: 0>}
      tt.descriptor_store %desc_acc[%off_m, %c0_i32], %5 {ttg.partition = array<i32: 0>} : !tt.tensordesc<128x128xf16, #shared>, tensor<128x128xf16, #blocked1>
      %6 = tt.addptr %l_i_ptr, %off_m {ttg.partition = array<i32: 0>} : !tt.ptr<f16>, i32
      %7 = tt.splat %6 {ttg.partition = array<i32: 0>} : !tt.ptr<f16> -> tensor<128x!tt.ptr<f16>, #blocked>
      %8 = tt.addptr %7, %3 {ttg.partition = array<i32: 0>} : tensor<128x!tt.ptr<f16>, #blocked>, tensor<128xi32, #blocked>
      %9 = arith.truncf %acc_10#1 {ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>> to tensor<128xf16, #ttg.slice<{dim = 1, parent = #linear}>>
      %10 = ttg.convert_layout %9 {ttg.partition = array<i32: 0>} : tensor<128xf16, #ttg.slice<{dim = 1, parent = #linear}>> -> tensor<128xf16, #blocked>
      tt.store %8, %10 {ttg.partition = array<i32: 0>} : tensor<128x!tt.ptr<f16>, #blocked>
      %11 = tt.addptr %m_i_ptr, %off_m {ttg.partition = array<i32: 0>} : !tt.ptr<f16>, i32
      %12 = tt.splat %11 {ttg.partition = array<i32: 0>} : !tt.ptr<f16> -> tensor<128x!tt.ptr<f16>, #blocked>
      %13 = tt.addptr %12, %3 {ttg.partition = array<i32: 0>} : tensor<128x!tt.ptr<f16>, #blocked>, tensor<128xi32, #blocked>
      %14 = arith.truncf %acc_10#0 {ttg.partition = array<i32: 0>} : tensor<128xf32, #ttg.slice<{dim = 1, parent = #linear}>> to tensor<128xf16, #ttg.slice<{dim = 1, parent = #linear}>>
      %15 = ttg.convert_layout %14 {ttg.partition = array<i32: 0>} : tensor<128xf16, #ttg.slice<{dim = 1, parent = #linear}>> -> tensor<128xf16, #blocked>
      tt.store %13, %15 {ttg.partition = array<i32: 0>} : tensor<128x!tt.ptr<f16>, #blocked>
      %tile_idx_13 = arith.addi %tile_idx_6, %num_sm {ttg.partition = array<i32: 0, 2>} : i32
      // The epilogue token and evolved phase state seed the next tile.
      scf.yield {ttg.partition = array<i32: 0, 1, 2>} %tile_idx_13 : i32
    } {tt.num_stages = 2 : i32, tt.warp_specialize, ttg.partition = array<i32: 0, 1, 2>, ttg.partition.outputs = [array<i32: 0, 2>], ttg.partition.stages = [0 : i32, 1 : i32, 0 : i32], ttg.warp_specialize.tag = 0 : i32}
    tt.return
  }
}

//--- completion.mlir
#blocked = #ttg.blocked<{sizePerThread = [1, 8], threadsPerWarp = [4, 8], warpsPerCTA = [4, 1], order = [1, 0]}>
#linear = #ttg.linear<{register = [[0, 1], [0, 2], [0, 4], [0, 8], [0, 16], [0, 32], [32, 0], [64, 0]], lane = [[1, 0], [2, 0], [4, 0], [8, 0], [16, 0]], warp = [[0, 0], [0, 0]], block = []}>
#shared = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 16}>
#smem = #ttg.shared_memory

module attributes {"ttg.num-ctas" = 1 : i32, "ttg.num-warps" = 4 : i32, ttg.target = "cuda:100", "ttg.threads-per-warp" = 32 : i32} {
  // TMA-LABEL: @converted_descriptor_store_completion
  // Bind EMPTY through the initial producer wait, independently of FULL.
  // TMA: [[STORE_EMPTY:%.*]] = ttg.local_alloc : () -> !ttg.memdesc<1x1xi64,
  // TMA: [[STORE_ENTRY:%.*]] = ttg.memdesc_index [[STORE_EMPTY]][{{%.*}}] {ttg.partition = array<i32: 0>, ttg.warp_specialize.tag = 0 : i32}
  // TMA-NEXT: ttng.wait_barrier [[STORE_ENTRY]],
  tt.func @converted_descriptor_store_completion(%desc: !tt.tensordesc<128x64xf16, #shared>, %i: i32, %lb: i32, %ub: i32, %step: i32) {
    %alloc = ttg.local_alloc {buffer.id = 601 : i32} : () -> !ttg.memdesc<128x64xf16, #shared, #smem, mutable>
    scf.for %iv = %lb to %ub step %step : i32 {
      %first = "producer"() {ttg.partition = array<i32: 0>} : () -> tensor<128x64xf16, #linear>
      ttg.local_store %first, %alloc {ttg.partition = array<i32: 0>} : tensor<128x64xf16, #linear> -> !ttg.memdesc<128x64xf16, #shared, #smem, mutable>
      // TMA: [[STORE_READ:%.*]] = ttg.memdesc_index {{%.*}}[[[STORE_SLOT:%[a-zA-Z0-9_]+]]] {ttg.partition = array<i32: 1>} : !ttg.memdesc<1x128x64xf16,
      // TMA-NEXT: {{%.*}} = ttg.local_load [[STORE_READ]]
      %loaded = ttg.local_load %alloc {ttg.partition = array<i32: 1>} : !ttg.memdesc<128x64xf16, #shared, #smem, mutable> -> tensor<128x64xf16, #linear>
      %converted = ttg.convert_layout %loaded {ttg.partition = array<i32: 1>} : tensor<128x64xf16, #linear> -> tensor<128x64xf16, #blocked>
      // The consumer release comes AFTER the descriptor store even with the
      // intervening layout conversion between the load and the store.
      // The lowered descriptor read completes before its ownership release.
      // TMA: ttng.async_tma_copy_local_to_global
      // TMA-NEXT: ttng.async_tma_store_wait {pendings = 0 : i32}
      // TMA-NEXT: [[STORE_RETURN:%.*]] = ttg.memdesc_index [[STORE_EMPTY]][[[STORE_SLOT]]] {ttg.partition = array<i32: 1>}
      // TMA-NEXT: ttng.arrive_barrier [[STORE_RETURN]], 1 {ttg.partition = array<i32: 1>}
      tt.descriptor_store %desc[%i, %i], %converted {ttg.partition = array<i32: 1>} : !tt.tensordesc<128x64xf16, #shared>, tensor<128x64xf16, #blocked>
      %next = "producer"() {ttg.partition = array<i32: 0>} : () -> tensor<128x64xf16, #linear>
      ttg.local_store %next, %alloc {ttg.partition = array<i32: 0>} : tensor<128x64xf16, #linear> -> !ttg.memdesc<128x64xf16, #shared, #smem, mutable>
    } {tt.warp_specialize, ttg.partition = array<i32: 0, 1>, ttg.warp_specialize.tag = 0 : i32}
    tt.return
  }
}

//--- startup.mlir
// The startup relay survives peeling and subsequent buffer reuse.

#reg1 = #ttg.blocked<{sizePerThread = [1], threadsPerWarp = [32], warpsPerCTA = [4], order = [0]}>
#shared1 = #ttg.swizzled_shared<{vec = 1, perPhase = 1, maxPhase = 1, order = [0]}>
#reg = #ttg.blocked<{sizePerThread = [1, 128], threadsPerWarp = [32, 1], warpsPerCTA = [4, 1], order = [0, 1]}>
#shared = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 16}>
#tmem = #ttng.tensor_memory_encoding<blockM = 128, blockN = 128, colStride = 1>
#smem = #ttg.shared_memory
#tm = #ttng.tensor_memory
!acc = !ttg.memdesc<128x128xf32, #tmem, #tm, mutable>
!tile = tensor<128x128xf32, #reg>
!lhs = !ttg.memdesc<128x64xf16, #shared, #smem>
!rhs = !ttg.memdesc<64x128xf16, #shared, #smem>

module attributes {"ttg.num-warps" = 4 : i32, ttg.target = "cuda:100"} {
  // PIPE-LABEL: @scheduled_reader_first
  // PIPE: [[PIPE_TMEM:%.*]] = ttng.tmem_alloc
  // PIPE: [[PIPE_READY:%.*]] = ttg.local_alloc : () -> !ttg.memdesc<1x1xi64,
  // PIPE: [[PIPE_TO_MMA:%.*]] = ttg.local_alloc : () -> !ttg.memdesc<1x1xi64,
  // PIPE: ttg.warp_specialize
  // PIPE: default {
  // PIPE: [[PIPE_ENTRY:%.*]] = ttg.memdesc_index [[PIPE_READY]][
  // PIPE-NEXT: ttng.wait_barrier [[PIPE_ENTRY]],
  // PIPE-NEXT: {{.*}}scf.for
  // The pipeliner peels the first correction into the prologue. The enclosing
  // reservation must arrive before its first wait/read, not just a later wait
  // inside the recurrence. CSE reuses the entry arrival's barrier view.
  // PIPE-NOT: ttng.wait_barrier
  // PIPE-NOT: ttng.tmem_load
  // PIPE: [[PIPE_RELAY:%.*]] = ttg.memdesc_index [[PIPE_READY]][
  // PIPE-NEXT: ttng.arrive_barrier [[PIPE_RELAY]], 1
  // PIPE-NOT: scf.for
  // PIPE-NOT: ttng.wait_barrier
  // PIPE-NOT: ttng.tmem_load
  // PIPE: ttng.wait_barrier [[PIPE_RELAY]],
  // PIPE-NEXT: [[PIPE_FIRST_TILE:%.*]] = ttg.memdesc_index [[PIPE_TMEM]][
  // PIPE-NEXT: {{.*}}ttng.tmem_load [[PIPE_FIRST_TILE]][]
  // PIPE-NEXT: [[PIPE_FIRST_VALUE:%.*]] = math.exp2
  // PIPE-NEXT: {{.*}}ttng.tmem_store [[PIPE_FIRST_VALUE]], [[PIPE_FIRST_TILE]][]
  // PIPE-NEXT: [[PIPE_FIRST_DONE:%.*]] = ttg.memdesc_index [[PIPE_TO_MMA]][
  // PIPE-NEXT: ttng.arrive_barrier [[PIPE_FIRST_DONE]], 1
  // The inner recurrence keeps the same wait/correction/completion protocol.
  // PIPE-NEXT: [[PIPE_INNER:%[a-zA-Z0-9_]+]]:2 = scf.for
  // PIPE: [[PIPE_WAIT:%.*]] = ttg.memdesc_index [[PIPE_READY]][
  // PIPE-NEXT: ttng.wait_barrier [[PIPE_WAIT]],
  // PIPE-NEXT: [[PIPE_TILE:%.*]] = ttg.memdesc_index [[PIPE_TMEM]][
  // PIPE-NEXT: {{.*}}ttng.tmem_load [[PIPE_TILE]][]
  // PIPE-NEXT: [[PIPE_VALUE:%.*]] = math.exp2
  // PIPE-NEXT: {{.*}}ttng.tmem_store [[PIPE_VALUE]], [[PIPE_TILE]][]
  // PIPE-NEXT: [[PIPE_DONE:%.*]] = ttg.memdesc_index [[PIPE_TO_MMA]][
  // PIPE-NEXT: ttng.arrive_barrier [[PIPE_DONE]], 1
  // PIPE: scf.yield
  // The final observer reacquires READY at the returned slot before the next
  // outer iteration inherits that slot and the updated phase state.
  // PIPE: [[PIPE_FINAL_WAIT:%.*]] = ttg.memdesc_index [[PIPE_READY]][[[PIPE_INNER]]#0]
  // PIPE-NEXT: ttng.wait_barrier [[PIPE_FINAL_WAIT]],
  // PIPE-NEXT: [[PIPE_FINAL_TILE:%.*]] = ttg.memdesc_index [[PIPE_TMEM]][[[PIPE_INNER]]#0]
  // PIPE-NEXT: [[PIPE_FINAL_VALUE:%.*]], {{%.*}} = ttng.tmem_load [[PIPE_FINAL_TILE]][]
  // PIPE-NEXT: "consume"([[PIPE_FINAL_VALUE]])
  // PIPE-NEXT: scf.yield {{%.*}}, [[PIPE_INNER]]#0, {{%.*}} : !ttg.async.token, i32, i32
  tt.func @scheduled_reader_first(%lhs: !lhs, %rhs: !rhs, %guard: i1) {
    %c0 = arith.constant 0 : i32
    %c1 = arith.constant 1 : i32
    %c2 = arith.constant 2 : i32
    %c4 = arith.constant 4 : i32
    %true = arith.constant true
    %false = arith.constant false
    %zero = arith.constant dense<0.0> : !tile
    %acc, %alloc_tok = ttng.tmem_alloc {buffer.copy = 1 : i32, buffer.id = 100 : i32} : () -> (!acc, !ttg.async.token)
    scf.for %i = %c0 to %c2 step %c1 : i32 {
      // Scheduled reader and MMA stages require the same incoming-permit relay.
      %inner:2 = scf.for %j = %c0 to %c2 step %c1 iter_args(%carry = %alloc_tok, %use_acc = %false) -> (!ttg.async.token, i1) : i32 {
        %value, %read = ttng.tmem_load %acc[%carry] {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : !acc -> !tile
        %corrected = math.exp2 %value {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : !tile
        %written = ttng.tmem_store %corrected, %acc[%read], %true {loop.cluster = 1 : i32, loop.stage = 0 : i32, ttg.partition = array<i32: 0>} : !tile -> !acc
        %mma = ttng.tc_gen5_mma %lhs, %rhs, %acc[%written], %use_acc, %true {loop.cluster = 1 : i32, loop.stage = 1 : i32, ttg.partition = array<i32: 1>} : !lhs, !rhs, !acc
        scf.yield {ttg.partition = array<i32: 0, 1>} %mma, %true : !ttg.async.token, i1
      } {tt.scheduled_max_stage = 1 : i32, ttg.partition = array<i32: 0, 1>, ttg.partition.outputs = [array<i32: 1>, array<i32: 1>]}
      %out, %read_out = ttng.tmem_load %acc[%inner#0] {ttg.partition = array<i32: 0>} : !acc -> !tile
      "consume"(%out) {ttg.partition = array<i32: 0>} : (!tile) -> ()
    } {tt.warp_specialize, ttg.partition = array<i32: 0, 1>, ttg.partition.stages = [0 : i32, 0 : i32], ttg.warp_specialize.tag = 0 : i32}
    tt.return
  }
}

//--- observer.mlir
#blocked = #ttg.blocked<{sizePerThread = [1, 128], threadsPerWarp = [32, 1], warpsPerCTA = [4, 1], order = [0, 1]}>
#shared = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = false, elementBitWidth = 16}>
#shared1 = #ttg.nvmma_shared<{swizzlingByteWidth = 128, transposed = true, elementBitWidth = 16}>
#smem = #ttg.shared_memory
#tmem = #ttng.tensor_memory_encoding<blockM = 128, blockN = 128, colStride = 1>

module attributes {"ttg.num-warps" = 4 : i32, ttg.target = "cuda:100"} {
  // LOWER-LABEL: @post_ws_tmem_read_tag
  // PARTITION-LABEL: @post_ws_tmem_read_tag
  tt.func @post_ws_tmem_read_tag(
      %ub: i32,
      %lhs: !ttg.memdesc<128x64xf16, #shared, #smem>,
      %rhs: !ttg.memdesc<64x128xf16, #shared1, #smem>) {
    %cst = arith.constant dense<0.000000e+00> : tensor<128x128xf32, #blocked>
    %c0 = arith.constant 0 : i32
    %c1 = arith.constant 1 : i32
    %true = arith.constant true
    %acc, %tok = ttng.tmem_alloc : () -> (!ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable>, !ttg.async.token)
    // LOWER: [[READ:%.*]] = ttg.memdesc_index {{.*}} : !ttg.memdesc<1x128x128xf32
    // LOWER: ttng.tmem_store {{.*}}, [[READ]][]
    %init = ttng.tmem_store %cst, %acc[%tok], %true : tensor<128x128xf32, #blocked> -> !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable>
    // The same semaphore token remains live across the loop. Every MMA uses
    // its buffer, and one release after the loop tracks the final MMA.
    // PARTITION: nvws.warp_group
    %loop = scf.for %iv = %c0 to %ub step %c1 iter_args(%carry = %init) -> (!ttg.async.token) : i32 {
      %mma = ttng.tc_gen5_mma %lhs, %rhs, %acc[%carry], %true, %true {ttg.partition = array<i32: 1>} : !ttg.memdesc<128x64xf16, #shared, #smem>, !ttg.memdesc<64x128xf16, #shared1, #smem>, !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable>
      scf.yield {ttg.partition = array<i32: 1>} %mma : !ttg.async.token
    } {tt.num_stages = 2 : i32, tt.warp_specialize, ttg.partition = array<i32: 0, 1>, ttg.partition.outputs = [array<i32: 1>], ttg.partition.stages = [0 : i32, 0 : i32], ttg.warp_specialize.tag = 0 : i32}
    // LOWER: ttng.tc_gen5_commit {{.*}} {ttg.partition = array<i32: 1>, ttg.warp_specialize.tag = 0 : i32}
    // LOWER: ttng.wait_barrier {{.*}} :
    // LOWER: [[OUT:%.*]], {{%.*}} = ttng.tmem_load [[READ]][]
    // PARTITION: ttng.tc_gen5_commit {{.*}} {ttg.partition = array<i32: 1>, ttg.warp_specialize.tag = 0 : i32}
    // PARTITION: nvws.warp_group.return
    // PARTITION: [[POST_READ:%.*]] = ttg.memdesc_index {{.*}} : !ttg.memdesc<1x128x128xf32
    // PARTITION: [[POST_OUT:%.*]], {{%.*}} = ttng.tmem_load [[POST_READ]][]
    %out, %load_tok = ttng.tmem_load %acc[%loop] : !ttg.memdesc<128x128xf32, #tmem, #ttng.tensor_memory, mutable> -> tensor<128x128xf32, #blocked>
    // The post-loop read is the final access.
    // LOWER-NEXT: "use"([[OUT]])
    // PARTITION-NEXT: "use"([[POST_OUT]])
    "use"(%out) : (tensor<128x128xf32, #blocked>) -> ()
    tt.return
  }
}
