name: Meta Triton TritonBench Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  mi350-tritonbench-test:
    if: github.repository_owner == 'facebookexperimental'
    runs-on: linux-fb-triton-mi350-1
    env:
      CONDA_ENV: meta-triton
    timeout-minutes: 240
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
