name: Meta Triton MI350 Tests
on:
  push:
    branches:
      - main
  pull_request:

env:
  MAX_JOBS: 16
  TORCH_NIGHTLY_URL: https://download-r2.pytorch.org/whl/nightly/rocm7.2/torch-2.13.0.dev20260513%2Brocm7.2-cp312-cp312-manylinux_2_28_x86_64.whl

jobs:
  mi350-meta-triton-test:
    if: github.repository_owner == 'facebookexperimental'
    runs-on: linux-fb-triton-mi350-1
    env:
      WORKSPACE_DIR: /workspace
      CONDA_ENV: pytorch
      UV_VENV_DIR: /workspace/uv_venvs
      SETUP_SCRIPT: /workspace/setup_instance.sh
    timeout-minutes: 240
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout Tritonbench
        uses: actions/checkout@v3
        with:
          repository: meta-pytorch/tritonbench
          ref: xz9/add-install-wheel
          path: tritonbench
          submodules: recursive
      - name: Setup Tritonbench environment
        working-directory: tritonbench
        run: |
          set -eux
          bash ./.ci/tritonbench/setup-env.sh --hip --custom-triton "${GITHUB_WORKSPACE}" --install-torch-wheel "${TORCH_NIGHTLY_URL}"
      - name: Run TritonBench
        working-directory: tritonbench
        run: |
          set -eux
          . "${SETUP_SCRIPT}"
          bash ./.ci/tritonbench/test-gpu.sh

  mi350-tlx-test:
    if: github.repository_owner == 'facebookexperimental'
    runs-on: linux-fb-triton-mi350-1
    env:
      WORKSPACE_DIR: /workspace
      CONDA_ENV: pytorch
      UV_VENV_DIR: /workspace/uv_venvs
      SETUP_SCRIPT: /workspace/setup_instance.sh
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout Tritonbench
        uses: actions/checkout@v3
        with:
          repository: meta-pytorch/tritonbench
          ref: xz9/add-install-wheel
          path: tritonbench
          submodules: recursive
      - name: Setup Tritonbench environment
        working-directory: tritonbench
        run: |
          set -eux
          bash ./.ci/tritonbench/setup-env.sh --hip --custom-triton "${GITHUB_WORKSPACE}" --install-torch-wheel "${TORCH_NIGHTLY_URL}"
      - name: Run TLX unit tests
        timeout-minutes: 5
        run: |
          set -eux
          . "${SETUP_SCRIPT}"
          uv pip install pytest
          pytest python/test/unit/language/test_tlx_*.py -v

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
