name: Meta Triton TLX Tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  h100-tlx-test:
    if: github.repository_owner == 'facebookexperimental'
    runs-on: [linux.gcp.h100]
    timeout-minutes: 240
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tune Nvidia GPU
        run: |
          sudo nvidia-smi -pm 1
          sudo ldconfig
          nvidia-smi
